EMS/EMS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('backstage.urls')),
    path('scoreManagement/', include('scoreManagement.urls')),
    path('courseSelection/', include('courseSelection.urls')),
    path('courseScheduling/', include('courseScheduling.urls')),
    path('graduationManagement/', include('graduationManagement.urls')),
    # path('captcha/', include('captcha.urls')),
    # path(r'courseScheduling', include('courseScheduling.urls')),
    # path(r'courseSelection', include('courseSelection.urls')),
    # path(r'graduationManagement', include('graduationManagement.urls')),
    # path(r'scoreManagement', include('scoreManagement.urls')),
]

EMS/backstage/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings

app_name = "backstage"
urlpatterns = [
                path('welcome', views.welcome, name="welcome"),
                path('', views.goto_login, name='goto_login'),
                url(r'^mylogin/$', views.mylogin, name='mylogin'),
                url(r'^mylogout/$', views.mylogout, name='mylogout'),
                url(r'^register/$', views.register, name='register'),
                # path('register_t/', views.register_t, name='register_t'),
                # path('homepage/', views.homepage, name='homepage'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EMS/courseSelection/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'courseSelection'
urlpatterns = [
                path('stuSelect',views.stuSelect,name="stuSelect"),
                  path('', views.welcome, name="welcome"),
              ]

EMS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('backstage.urls')),
    path('scoreManagement/', include('scoreManagement.urls')),
    path('courseSelection/', include('courseSelection.urls')),
    path('courseScheduling/', include('courseScheduling.urls')),
    path('graduationManagement/', include('graduationManagement.urls')),
    # path('captcha/', include('captcha.urls')),
    # path(r'courseScheduling', include('courseScheduling.urls')),
    # path(r'graduationManagement', include('graduationManagement.urls')),
    # path(r'scoreManagement', include('scoreManagement.urls')),
]

courseScheduling/urls.py
from django.conf.urls import url
from django.urls import include, path
from . import views


app_name = 'courseScheduling'
urlpatterns = [
                  path('', views.welcome, name="welcome"),
                  path('scheduling_home_page', views.scheduling_home_page, name="scheduling_home_page"),
              ]

courseSelection/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'courseSelection'
urlpatterns = [

                  path('', views.welcome, name="welcome"),
                  path('selection_home_page', views.selection_home_page, name="selection_home_page"),
                  path('stu_tongshi', views.stu_tongshi, name="stu_tongshi"),
                  path('stu_major', views.stu_major, name="stu_major"),
                  # path('resultAdd',views.resultAdd,name="resultAdd"),
                  path('teacher_course', views.teacher, name="teacher_course"),
                  path('select_course', views.select_course, name="select_course"),
                  path('delete_course', views.delete, name="delete_course"),
                  path('find_course', views.find_course, name="find_course"),

                  path('adm_selection_manage', views.adm_selection_manage, name="adm_selection_manage"),
                  path('adm_class', views.adm_class, name="adm_class"),
                  path('adm_school', views.adm_school, name="adm_school"),
                  path('text', views.text, name="text"),
                  path('school_query', views.school_query, name="school_query"),
                  path('class_query', views.class_query, name="class_query"),
                  path('time_set', views.time_set, name="time_set")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

graduationManagement/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'graduationManagement'
urlpatterns = [
                  path('', views.welcome, name="welcome"),
                  path('graduation_home_page', views.graduation_home_page, name="graduation_home_page"),
                  path('student_choose_project',views.student_choose_project,name="student_choose_project"),
                  path('student_submit_project',views.student_submit_project,name="student_submit_project"),
                  path('teacher_edit_project',views.teacher_edit_project,name="teacher_edit_project"),
                  path('student_view_score',views.student_view_score,name="student_view_score")
              ]

scoreManagement/urls.py
from django.urls import path, include

from django.conf.urls import url
from . import views

app_name = 'scoreManagement'
urlpatterns = [
    path('welcome', views.welcome, name="welcome"),
    path('score_home_page', views.score_home_page, name="score_home_page"),
    path('student_score', views.student_score, name="student_score"),
    path('student_own_study', views.student_own_study, name="student_own_study"),
    path('adm_all_course_score', views.adm_all_course_score,
         name="adm_all_course_score"),
    path('std_view_major_course', views.std_view_major_course,
         name="std_view_major_course"),
    path('std_view_major_plan', views.std_view_major_plan,
         name="std_view_major_plan"),
    path('assess_teacher', views.assess_teacher, name="assess_teacher"),
    path('submit_result', views.submit_result, name="submit_result"),
    path('submit_all', views.submit_all, name="submit_all"),
    path('teacher_view_teaching', views.teacher_view_teaching, name="teacher_view_teaching"),
    path('teacher_upload_score', views.teacher_upload_score, name="teacher_upload_score"),
]

EMS/backstage/models.py
from django.db import models
from django.contrib.auth.models import User


# 学院
class College(models.Model):
    # 学院名
    name = models.CharField(unique=True, max_length=128)
    # 学院简称
    short_name = models.CharField(unique=True, max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'college'


# 专业
class Major(models.Model):
    # 专业代码,如0403。
    # 04是所在学院的排序，03是专业在院中的排序
    mno = models.CharField(unique=True, max_length=20)
    # 专业名称，唯一，如：计算机科学与技术， 化学工程与工艺
    mname = models.CharField(max_length=128, default="")
    # 专业简称，如：计算机科学与技术--计科， 化学工程与工业--化工
    short_name = models.CharField(max_length=20)
    # 所属学院，外键
    in_college = models.ForeignKey(to=College, on_delete=models.CASCADE)

    def __str__(self):
        return "-".join([self.mno, self.mname])

    class Meta:
        db_table = 'major'
        unique_together = (
            'mno',
            'mname'
        )


# 专业信息
class MajorPlan(models.Model):
    # 学年，该专业下的那个年级的学生
    year = models.IntegerField()
    # 专业名称，对应了需要的专业
    major = models.ForeignKey(to=Major, on_delete=models.CASCADE)
    # 专业计划班级数
    cls_num = models.IntegerField()
    # 专业计划人数
    people_num = models.IntegerField()
    # 毕业最低学分
    score_grad = models.IntegerField()
    # 学制：毕业需要学习的年数, 4
    stu_years = models.IntegerField()
    # 该年级专业需要修学的课程数,80, 88...
    course_num = models.IntegerField()

    def __str__(self):
        return str(self.year) + '-' + str(self.major)

    class Meta:
        db_table = 'major_plan'
        unique_together = (
            'year', 'major'
        )


# 行政班
class AdmClass(models.Model):
    # 行政班名，如：计科1605
    name = models.CharField(max_length=10, unique=True)
    # 行政班所属专业，由 major.short_name + in_year + 编号（自增）构成
    # 例如：计科1605， 化工1606
    major = models.ForeignKey(to=MajorPlan, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'adm_class'


# 学生
class Student(User):
    # 学生姓名
    name = models.CharField(max_length=128)
    # 学号，必须10位，例如：2016011186
    # username = models.CharField()
    # 登录所需密码，初始密码设置为学号
    # password = models.CharField()
    # 学生性别
    sex = models.BooleanField(default=True)
    # 目前已修学分
    score_got = models.IntegerField()
    # 所在的行政班级，外键
    in_cls = models.ForeignKey(to=AdmClass, on_delete=models.CASCADE)

    # 入学年份，用int表示即可，该学生入学的年份
    # 考虑可能留级的情况，入学年份与专业年级不对应
    in_year = models.IntegerField()

    def __str__(self):
        return "-".join([self.username, self.name])

    class Meta:
        db_table = 'student'


# 教师
class Teacher(User):
    # 教师姓名
    name = models.CharField(max_length=128)
    # username, 自带字段
    # 同时也就是教师工号，设置为9位，与学生区分
    # password, 自带字段，默认与工号相同
    sex = models.BooleanField(default=True)
    # 教师所属学院
    college = models.ForeignKey(to=College, on_delete=models.CASCADE)
    # 教师入职的年份
    in_year = models.IntegerField()
    # 学历，在个人信息中显示。如：博士，博士后...
    edu_background = models.CharField(null=True, max_length=128)
    # 在校职位，如：教授，副教授，讲师等
    title = models.CharField(default='讲师', max_length=128)
    # 教师个人简介，可空
    description = models.TextField(null=True)

    def __str__(self):
        return "-".join([self.username, self.name])

    class Meta:
        db_table = 'teacher'


# 教室
class ClassRoom(models.Model):
    # 教室编号，如：A-302， B阶-202
    crno = models.CharField(primary_key=True, max_length=128)
    # 教室类型，阶教180人，中等教室120人，小教室50人
    # 教室类型需要和教室编号对应
    crtype = models.CharField(null=False, max_length=10)

    # 教室能够容纳的学生数目，需要与类型对应
    contain_num = models.IntegerField()

    def __str__(self):
        return self.crno

    class Meta:
        db_table = 'class_room'

EMS/courseScheduling/models.py
from django.db import models
from backstage.models import Student, Teacher
from scoreManagement.models import Teaching, MajorCourses

EMS/courseSelection/models.py
from django.db import models
from django.db import models

# Create your models here.

from backstage.models import Teacher, Student,\
    College, MajorPlan, AdmClass, ClassRoom
from scoreManagement.models import Course,MajorCourses,Teaching

class courseSelected(models.Model):
    sno = models.ForeignKey(to=Student,on_delete=models.CASCADE)
    course = models.ForeignKey(to=MajorCourses,on_delete=models.CASCADE)
    tno = models.ForeignKey(to=Teacher,on_delete=models.CASCADE)
    time = models.CharField(max_length=20)
    classroom = models.CharField(max_length=20)
    score = models.FloatField()

class TeachersCourse(models.Model):
    tno = models.ForeignKey(to=Teacher,on_delete=models.CASCADE)
    course = models.ForeignKey(to=MajorCourses,on_delete=models.CASCADE)
    stu_num = models.IntegerField()

courseSelection/models.py
from django.db import models
from django.db import models
from courseScheduling.models import Teacher_Schedule_result
# Create your models here.

from backstage.models import Teacher, Student, \
    College, MajorPlan, AdmClass, ClassRoom
from scoreManagement.models import Course, MajorCourses, Teaching


class CourseSelected(models.Model):
    sno = models.ForeignKey(to=Student, on_delete=models.CASCADE)
    cno = models.ForeignKey(to=Teacher_Schedule_result, on_delete=models.CASCADE)
    score = models.FloatField()
    common_score = models.FloatField(null=True)
    final_score = models.FloatField(null=True)

    class Meta:
        db_table = "course_selected"


class Picture(models.Model):
    pic = models.ImageField(upload_to='static/img/adm_query')

    def __str__(self):
        return self.pic


class BEGIN_AND_END_TIME:
    begin_time = models.ForeignKey(to=AdmClass, on_delete=models.CASCADE)
    end_time = models.ForeignKey(to=AdmClass, on_delete=models.CASCADE)

    def __str__(self):
        return self.begin_time + '-->' + self.end_time

    class Meta:
        db_table = "time"

EMS/backstage/views.py
import os
from django.contrib.auth import authenticate, login, logout, models
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, get_object_or_404


from backstage.models import Student, Teacher, User
from utils import make_encode


def welcome(request):
    name = request.session['name']
    user_type = request.session['user_type']
    context = {
        'name': name,
        'user_type': user_type
    }
    return render(request, 'base.html', context)


def goto_login(request):
    return render(request, 'login.html')


@csrf_exempt
def mylogin(request):

    def save_session(user_type):
        request.session['username'] = username
        request.session['name'] = user.name
        request.session['password'] = password
        request.session['user_type'] = user_type

    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 对密码进行加密
        password = make_encode(password)
        if 10 == len(username):
            # 学号的长度是10位
            try:
                user = Student.objects.get(username=username, password=password)
                login(request, user)
                save_session('学生')
                return redirect('backstage:welcome')
            except:
                return JsonResponse({})
        elif 9 == len(username):
            try:
                user = Student.objects.get(username=username, password=password)
                login(request, user)
                save_session('学生')
                return redirect('backstage:welcome')
            except:
                return JsonResponse({})
        else:
            try:
                user = User.objects.get(username=username, password=password)
                login(request, user)
                save_session('管理员')
                return redirect('backstage:welcome')
            except:
                return JsonResponse({})


def student_view(request):
    raise NotImplemented


def admin_view(request):
    raise NotImplemented


def teacher_view(request):
    raise NotImplemented


@login_required
def mylogout(request):
    logout(request)
    return render(request, 'base.html')


@login_required
def register(request):
    raise NotImplemented

EMS/courseScheduling/views.py
from django.shortcuts import render


def welcome(request):
    return render(request, 'courseScheduing/welcome.html')

EMS/courseSelection/views.py
from django.shortcuts import render


def welcome(request):
    return render(request, 'courseSelection/welcome.html')

def stuSelect(request):
    pass

EMS/graduationManagement/views.py
from django.shortcuts import render
from django.http import HttpResponse


def welcome(request):
    return render(request, 'graduationManagement/welcome.html')

def func(request):
    return HttpResponse("func")

EMS/scoreManagement/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from backstage.models import Student, Teacher, College, Major, MajorPlan, ClassRoom, AdmClass
from scoreManagement.models import Course, MajorPlan, MajorCourses


def welcome(request):
    students = Student.objects.all()
    teachers = Teacher.objects.all()
    colleges = College.objects.all()
    majors = Major.objects.all()
    major_plans = MajorPlan.objects.all()
    class_rooms = ClassRoom.objects.all()

    context = {
        'students': students,
        'teachers': teachers,
    }
    return render(request, 'scoreManage/scoreManagement.html', context)

EMS/templates/courseSelection/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}首页{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Google Font -->
    {#  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">#}
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" href="data:;base64,=">
    <!-- Bootstrap 3.3.6 -->
    <link rel="shortcut icon" href="{% static 'assets/ico/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/font-awesome-4.6.3/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'plugins/ionicons-2.0.1/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

    <script src="{% static 'js/echarts.js' %}"></script>
    {#    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>#}
    {#    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>#}
{% block css %}{% endblock %}
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">

    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
{#      <span class="logo-mini">CD</span>#}
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>教务管理系统</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">MM</span>
      </a>


      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'courseSelection:stuSelect' %}">学生选课<span class="sr-only">(current)</span></a></li>
            <li><a href="#">查看课表<span class="sr-only">(current)</span></a></li>
            <li><a href="#" >查看专业培养计划<span class="sr-only">(current)</span></a></li>

          <!-- 用户信息: style can be found in dropdown.less -->
            <li class="dropdown tasks-menu">
                <a href="{% url 'backstage:mylogout' %}">
                    <i class="fa fa-coffee" href="#"></i>
                    <span>logout</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header" href="{% url 'backstage:mylogout' %}">登出</li>
                </ul>
          </li>
            {% if request.user.is_authenticated %}
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle pull-right image" data-toggle="dropdown">
              <img src="{% static 'dist/img/head.jpg' %}" style="width: 25px;height:25px;" class="user-image" alt="User Image">
              <span class="hidden-xs">您好！{{ user.name }}</span>
            </a>
          </li>
            {% else %}
            <li class="dropdown user user-menu">
            <a href="{% url 'backstage:goto_login' %}" class="dropdown-toggle pull-right image">
              <span class="hidden-xs">您尚未登录，请登录！</span>
            </a>
          </li>
            {% endif %}
          <!-- Control Sidebar Toggle Button -->
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
          {% if request.user.is_authenticated %}
        <div class="pull-left image">
          <img src="{% static 'dist/img/head.jpg' %}" style="width: 50px;height: 50px;" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ request.user.username }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
              {% else %}

          {% endif %}
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">导航栏</li>
        <li class="treeview">
          <a href="{% url 'backstage:welcome' %}">
            <i class="fa fa-dashboard"></i> <span>后台管理</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>

        <li class="treeview">
          <a href="{% url 'scoreManagement:welcome' %}">
            <i class="fa fa-table"></i> <span>成绩管理</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>

        <li class="treeview">
          <a href="{% url 'courseSelection:welcome' %}">
            <i class="fa fa-table"></i> <span>选课</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>

          <li class="treeview">
          <a href="{% url 'courseScheduling:welcome' %}">
            <i class="fa fa-table"></i> <span>排课</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>

          <li class="treeview">
          <a href="{% url 'graduationManagement:welcome' %}">
            <i class="fa fa-table"></i> <span>毕业设计</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

      {% block content %}


      {% endblock %}

  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2019-<a href="https://www.buct.edu.cn" target="_blank">Beijing University of Chemical Technology</a>.</strong> All rights
    reserved.
  </footer>


</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

{% block script %}{% endblock %}

</body>
</html>

EMS/templates/courseSelection/stuSelected.html
{% extends 'courseSelection/base.html' %}
{% load staticfiles %}
{% load static %}
{% block title %}选课子系统{% endblock %}
{% block css %}{% endblock %}
{% block content %}







{% endblock %}
{% block script %}{% endblock %}

EMS/templates/courseSelection/welcome.html
<<<<<<< HEAD
{% extends 'courseSelection/base.html' %}
{% load staticfiles %}
{% load static %}
{% block title %}选课子系统{% endblock %}
{% block css %}{% endblock %}
{% block content %}
 <div class="content-wrapper">
        <div class="page-title">
          <div>
            <h1><i class="fa fa-dashboard"></i> Dashboard</h1>
            <p>A free and modular admin template</p>
          </div>
          <div>
            <ul class="breadcrumb">
              <li><i class="fa fa-home fa-lg"></i></li>
              <li><a href="#">Dashboard</a></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <h3 class="card-title">Getting Started</h3>
              <p>Vali is a free and responsive dashboard theme built with Bootstrap, Pug.js (templating) and SASS. It's fully customizable and modular. You don't need to add the code, you will not use.</p>
              <p>The issue with the most admin themes out there is that if you will see their source code there are a hell lot of external CSS and javascript files in there. And if you try to remove a CSS or Javascript file some things stops working.</p>
              <p>That's why I made Vali. Which is a light weight yet expendable and good looking theme. The theme has all the features required in a dashboard theme but this features are built like plug and play module. Take a look at the <a href="http://pratikborsadiya.in/blog/vali-admin" target="_blank">documentation</a> about customizing the theme.</p>
              <p class="mt-40 mb-20"><a class="btn btn-primary icon-btn mr-10" href="http://pratikborsadiya.in/blog/vali-admin" target="_blank"><i class="fa fa-file"></i>Docs</a><a class="btn btn-info icon-btn mr-10" href="https://github.com/pratikborsadiya/vali-admin" target="_blank"><i class="fa fa-github"></i>GitHub</a><a class="btn btn-success icon-btn" href="https://github.com/pratikborsadiya/vali-admin/archive/master.zip" target="_blank"><i class="fa fa-download"></i>Download</a></p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card">
              <h3 class="card-title">Compatibility with frameworks</h3>
              <p>This theme is not built for a specific framework or technology like Angular or React etc. But due to it's modular nature it's very easy to incorporate it into any front-end or back-end framework like Angular, React or Laravel.</p>
              <p>Go to <a href="http://pratikborsadiya.in/blog/vali-admin" target="_blank">documentation</a> for more details about integrating this theme with various frameworks.</p>
              <p>The source code is available on GitHub. If anything is missing or weird please report it as an issue on <a href="https://github.com/pratikborsadiya/vali-admin" target="_blank">GitHub</a>. If you want to contribute to this theme pull requests are always welcome.</p>
            </div>
          </div>
        </div>
{% endblock %}
{% block script %}{% endblock %}


=======
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% block title %}选课子系统{% endblock %}
>>>>>>> b12887070dca45507f23fcc57d4d880354fe094e