EMS/EMS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('backstage.urls')),
    path('scoreManagement/', include('scoreManagement.urls')),
    path('courseSelection/', include('courseSelection.urls')),
    path('courseScheduling/', include('courseScheduling.urls')),
    path('graduationManagement/', include('graduationManagement.urls')),
    # path('captcha/', include('captcha.urls')),
    # path(r'courseScheduling', include('courseScheduling.urls')),
    # path(r'courseSelection', include('courseSelection.urls')),
    # path(r'graduationManagement', include('graduationManagement.urls')),
    # path(r'scoreManagement', include('scoreManagement.urls')),
]

EMS/courseSelection/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'courseSelection'
urlpatterns = [
                path('stuSelect',views.stuSelect,name="stuSelect"),
                  path('', views.welcome, name="welcome"),
              ]

EMS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('backstage.urls')),
    path('scoreManagement/', include('scoreManagement.urls')),
    path('courseSelection/', include('courseSelection.urls')),
    path('courseScheduling/', include('courseScheduling.urls')),
    path('graduationManagement/', include('graduationManagement.urls')),
    # path('captcha/', include('captcha.urls')),
    # path(r'courseScheduling', include('courseScheduling.urls')),
    # path(r'graduationManagement', include('graduationManagement.urls')),
    # path(r'scoreManagement', include('scoreManagement.urls')),
]

backstage/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings

app_name = "backstage"
urlpatterns = [
                  path('welcome', views.welcome, name="welcome"),
                  path('', views.goto_login, name='goto_login'),
                  path('mylogin', views.mylogin, name='mylogin'),
                  path('mylogout', views.mylogout, name='mylogout'),
                  path('register', views.register, name='register'),
                  path('hello_student', views.student_view, name='student_view'),
                  path('hello_teacher', views.teacher_view, name='teacher_view'),
                  path('hello_admin', views.admin_view, name='admin_view'),
                  path('backstage_manage', views.backstage_manage, name='backstage_manage'),
                  path('my_personal_details', views.my_personal_details, name='my_personal_details'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courseSelection/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'courseSelection'
urlpatterns = [

                  path('', views.welcome, name="welcome"),
                  path('selection_home_page', views.selection_home_page, name="selection_home_page"),
                  path('stu_tongshi', views.stu_tongshi, name="stu_tongshi"),
                  path('stu_major', views.stu_major, name="stu_major"),
                  # path('resultAdd',views.resultAdd,name="resultAdd"),
                  path('teacher_course', views.teacher, name="teacher_course"),
                  path('select_course', views.select_course, name="select_course"),
                  path('delete_course', views.delete, name="delete_course"),
                  path('find_course', views.find_course, name="find_course"),

                  path('adm_selection_manage', views.adm_selection_manage, name="adm_selection_manage"),
                  path('adm_class', views.adm_class, name="adm_class"),
                  path('adm_school', views.adm_school, name="adm_school"),
                  path('text', views.text, name="text"),
                  path('school_query', views.school_query, name="school_query"),
                  path('class_query', views.class_query, name="class_query"),
                  path('time_set', views.time_set, name="time_set")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

graduationManagement/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'graduationManagement'
urlpatterns = [
                  path('', views.welcome, name="welcome"),
                  path('graduation_home_page', views.graduation_home_page, name="graduation_home_page"),
                  path('student_choose_project',views.student_choose_project,name="student_choose_project"),
                  path('student_submit_project',views.student_submit_project,name="student_submit_project"),
                  path('teacher_edit_project',views.teacher_edit_project,name="teacher_edit_project"),
                  path('student_view_score',views.student_view_score,name="student_view_score")
              ]

scoreManagement/urls.py
from django.urls import path, include

from django.conf.urls import url
from . import views

app_name = 'scoreManagement'
urlpatterns = [
    path('welcome', views.welcome, name="welcome"),
    path('score_home_page', views.score_home_page, name="score_home_page"),
    path('student_score', views.student_score, name="student_score"),
    path('student_own_study', views.student_own_study, name="student_own_study"),
    path('adm_all_course_score', views.adm_all_course_score,
         name="adm_all_course_score"),
    path('std_view_major_course', views.std_view_major_course,
         name="std_view_major_course"),
    path('std_view_major_plan', views.std_view_major_plan,
         name="std_view_major_plan"),
    path('assess_teacher', views.assess_teacher, name="assess_teacher"),
    path('submit_result', views.submit_result, name="submit_result"),
    path('submit_all', views.submit_all, name="submit_all"),
    path('teacher_view_teaching', views.teacher_view_teaching, name="teacher_view_teaching"),
    path('teacher_upload_score', views.teacher_upload_score, name="teacher_upload_score"),
]

EMS/courseSelection/models.py
from django.db import models
from django.db import models

# Create your models here.

from backstage.models import Teacher, Student,\
    College, MajorPlan, AdmClass, ClassRoom
from scoreManagement.models import Course,MajorCourses,Teaching

class courseSelected(models.Model):
    sno = models.ForeignKey(to=Student,on_delete=models.CASCADE)
    course = models.ForeignKey(to=MajorCourses,on_delete=models.CASCADE)
    tno = models.ForeignKey(to=Teacher,on_delete=models.CASCADE)
    time = models.CharField(max_length=20)
    classroom = models.CharField(max_length=20)
    score = models.FloatField()

class TeachersCourse(models.Model):
    tno = models.ForeignKey(to=Teacher,on_delete=models.CASCADE)
    course = models.ForeignKey(to=MajorCourses,on_delete=models.CASCADE)
    stu_num = models.IntegerField()

EMS/courseSelection/views.py
from django.shortcuts import render


def welcome(request):
    return render(request, 'courseSelection/welcome.html')

def stuSelect(request):
    pass

courseSelection/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from backstage.models import Student, Teacher, College, Major, MajorPlan, ClassRoom, AdmClass
from scoreManagement.models import Course, MajorPlan, MajorCourses, CourseScore, Teaching
from courseScheduling.models import Teacher_Schedule_result
from courseSelection.models import CourseSelected
import json
import numpy as np
from django.conf import settings
from .models import Picture
import MySQLdb
import matplotlib.pyplot as plt
import matplotlib


def welcome(request):
    return render(request, 'courseSelection/welcome.html')


def selection_home_page(request):
    if request.session['user_type'] == '学生':
        return render(request, 'courseSelection/student_selection_manage.html')
    elif request.session['user_type'] == '教师':
        return render(request, 'courseSelection/teacher_selection_manage.html')
    else:
        return render(request, 'courseSelection/adm_selection_manage.html')


def stu_tongshi(request):
    return render(request, "courseSelection/stu_tongshi.html")


def stu_major(request):
    majorC = Teacher_Schedule_result.objects.all()[:3]
    data = []
    dat = []
    haveChosen = {}

    #     # crno = models.CharField(max_length=128)
    #     # crtype = models.CharField(null=False, max_length=10)
    #     # contain_num = models.IntegerField()
    sno = request.session["username"]
    courseChosen = CourseSelected.objects.filter(sno__username=sno)
    for c in courseChosen:
        tmp = {}
        haveChosen[c.cno.id] = 1
        tmp["id"] = c.cno.id
        tmp["课程号"] = c.cno.tno.mcno.cno.cno
        tmp["课程名"] = c.cno.tno.mcno.cno.cname
        tmp["学时"] = c.cno.tno.mcno.hour_total
        tmp["选课人数"] = c.cno.current_number
        tmp["课程容量"] = c.cno.MAX_number
        tmp["授课教师"] = c.cno.tno.tno.name
        tmp["上课教室"] = c.cno.where.crno
        tmp["上课时间"] = c.cno.time
        dat.append(tmp)
    for major in majorC:
        tmp = {}
        try:
            if haveChosen[major.id] == 1:
                tmp["if_chosen"] = 1
        except:
            tmp["if_chosen"] = 0
        tmp["id"] = major.id
        tmp["课程号"] = major.tno.mcno.cno.cno
        tmp["课程名"] = major.tno.mcno.cno.cname
        tmp["学时"] = major.tno.mcno.hour_total
        tmp["选课人数"] = major.current_number
        tmp["课程容量"] = major.MAX_number
        tmp["授课教师"] = major.tno.tno.name
        tmp["上课教室"] = major.where.crno
        tmp["上课时间"] = major.time
        if tmp["选课人数"] < tmp["课程容量"]:
            data.append(tmp)
    return render(request, "courseSelection/stu_major.html", {'data': json.dumps(data), 'dat': json.dumps(dat)})


def select_course(request):
    if request.is_ajax():
        if request.method == 'GET':
            print("asdasd")
            flag = 1
            ID = request.GET.get("id")
            sno = request.session["username"]
            X = np.zeros((25, 8, 14), dtype=np.int)
            confilict_candidate = CourseSelected.objects.filter(sno__username=sno)  # 选的不同的课
            tot = 0
            course_time = []  # 收集这些课程的上课时间
            for i in confilict_candidate:
                tmp = i.cno.time.split(",")  # 同一门课程在一周内不同的时间上
                for j in tmp:  # 一周内不同的天
                    dic = {}
                    district = j.split("-")
                    dic["周数"] = district[2] + "-" + district[3]
                    dic["节次"] = district[0] + "-" + district[1]
                    course_time.append(dic)
            for i in course_time:
                week = i["周数"].split("-")
                times = i["节次"].split("-")
                cstart = 0
                cend = 0
                Day = 0
                if int(times[1]) >= 1 and int(times[1]) <= 13:
                    Day = 1
                elif int(times[1]) >= 14 and int(times[1]) <= 26:
                    Day = 2
                elif int(times[1]) >= 27 and int(times[1]) <= 39:
                    Day = 3
                elif int(times[1]) >= 40 and int(times[1]) <= 52:
                    Day = 4
                elif int(times[1]) >= 53 and int(times[1]) <= 65:
                    Day = 5
                elif int(times[1]) >= 66 and int(times[1]) <= 78:
                    Day = 6
                elif int(times[1]) >= 79 and int(times[1]) <= 91:
                    Day = 7

                cstart = int(times[0]) % 13
                cend = int(times[1]) % 13

                if cstart == 0:
                    cstart = 13
                if cend == 0:
                    cend = 13
                X[int(week[0]):int(week[1]) + 1, Day, cstart:cend + 1] = 1

            stu_new = Student.objects.get(username=sno)
            teach = Teacher_Schedule_result.objects.get(id=ID)
            tmp = teach.time.split(",")
            single_course = []
            if teach.current_number >= teach.MAX_number:
                flag = 3
                return JsonResponse(
                    {"flag": flag, "tot": tot})
            else:
                for j in tmp:
                    dic = {}
                    district = j.split("-")
                    dic["周数"] = district[2] + "-" + district[3]
                    dic["节次"] = district[0] + "-" + district[1]
                    single_course.append(dic)

                for j in single_course:
                    week = j["周数"].split("-")
                    times = j["节次"].split("-")
                    cstart = 0
                    cend = 0
                    Day = 0
                    if int(times[1]) >= 1 and int(times[1]) <= 13:
                        Day = 1
                    elif int(times[1]) >= 14 and int(times[1]) <= 26:
                        Day = 2
                    elif int(times[1]) >= 27 and int(times[1]) <= 39:
                        Day = 3
                    elif int(times[1]) >= 40 and int(times[1]) <= 52:
                        Day = 4
                    elif int(times[1]) >= 53 and int(times[1]) <= 65:
                        Day = 5
                    elif int(times[1]) >= 66 and int(times[1]) <= 78:
                        Day = 6
                    elif int(times[1]) >= 79 and int(times[1]) <= 91:
                        Day = 7

                    cstart = int(times[0]) % 13
                    cend = int(times[1]) % 13
                    if cstart == 0:
                        cstart = 13
                    if cend == 0:
                        cend = 13

                    if np.sum(X[int(week[0]):int(week[1]) + 1, Day, cstart:cend + 1]) != 0:
                        flag = 0
                        print(flag)
                        break

                if (flag):
                    new_cord = CourseSelected()
                    new_cord.sno = stu_new
                    new_cord.cno = teach
                    new_cord.score = 0
                    new_cord.save()
                    tot = teach.current_number
                    tot += 1
                    Teacher_Schedule_result.objects.filter(id=ID).update(current_number=tot)

                return JsonResponse(
                    {"flag": flag, "tot": tot})


def delete(request):
    if request.is_ajax():
        if request.method == 'GET':
            ID = request.GET.get("id")
            sno = request.session["username"]
            teach = Teacher_Schedule_result.objects.get(id=ID)

            tot = teach.current_number
            tot -= 1
            print(ID)
            Teacher_Schedule_result.objects.filter(id=ID).update(current_number=tot)
            X = CourseSelected.objects.filter(sno__username=sno, cno_id=ID)
            X.delete()

            return JsonResponse({"flag": 1, "tot": tot, "ID": ID})


def teacher(request):  # 教师查看授课选课情况
    return render(request, "courseSelection/index.html")


def find_course(request):
    if request.is_ajax():
        if request.method == 'GET':
            sno = request.session["username"]
            theCourse = CourseSelected.objects.filter(sno__username=sno)

            course_time = []  # 收集这些课程的上课时间
            dic = {}
            tmp = {}
            for i in theCourse:
                tmp = i.cno.time.split(",")  # 同一门课程在一周内不同的时间上
                dic[i.cno.tno.mcno.cno.cname] = []
                for j in tmp:  # 一周内不同的天
                    tmp = {}
                    district = j.split("-")
                    tmp["周数"] = district[2] + "-" + district[3]
                    tmp["节次"] = district[0] + "-" + district[1]
                    dic[i.cno.tno.mcno.cno.cname].append(tmp)
            return JsonResponse({"dic": dic})


def adm_selection_manage(request):
    return render(request, "courseSelection/adm_selection_manage.html")


def adm_class(request):
    return render(request, "courseSelection/adm_class.html")


def adm_school(request):
    return render(request, "courseSelection/adm_school.html")


def text(request):
    return render(request, "courseSelection/text.html")


def show_pic(request):
    pic_obj = Picture.objects.get(id=1)
    return


def school_query(request):
    print(132420198479292475)

    print("12312fdskjgcasuidgfwui")
    time = request.POST.get("time")
    grade = request.POST.get("grade")
    college = request.POST.get("college")
    subject = request.POST.get("subject")

    print(time, grade, college, subject)
    db = MySQLdb.connect("localhost", "root", "root", "ems", charset='utf8')
    cursor = db.cursor()

    # 使用execute方法执行SQL语句
    cursor.execute("SELECT * FROM course")

    # 使用 fetchone() 方法获取一条数据

    results = cursor.fetchall()
    n = 0
    # print(results)
    final_id = 0
    final_cno = 0
    final_cname = ""
    final_ctype = ""
    final_cscore = 0
    final_college = 0
    target = "CSE32500C"
    for row in results:
        id1 = row[0]
        cno = row[1]
        cname = row[2]
        typ = row[3]
        score = row[4]
        college = row[5]
        n += 1

templates/courseSelection/adm_class.html
{% extends "base.html" %}
{% block title %}欢迎登录教务管理系统{% endblock %}

{% block custom_nav %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">信息查询 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'backstage:my_personal_details' %}">查看个人信息</a></li>
            <li><a href="#">查看个人课表</a></li>
            <li><a href="#">查看全校课表</a></li>
            <li><a href="#">查询空闲教室</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'scoreManagement:std_view_major_plan' %}">查看专业培养计划</a></li>
            <li><a href="{% url 'scoreManagement:std_view_major_course' %}">查看专业课程计划</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'scoreManagement:student_score' %}">查看考试成绩</a></li>
            <li><a href="{% url 'scoreManagement:student_own_study' %}">查看个人学业情况</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a href="{% url 'courseSelection:select_course' %}" class="dropdown-toggle" data-toggle="dropdown">选课 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'courseSelection:stu_tongshi' %}">通识课</a></li>
            <li><a href="{% url 'courseSelection:stu_major' %}">专业选修</a></li>
            <li><a href="{% url 'courseSelection:adm_selection_manage' %}">管理员界面</a></li>

            <li><a href="#">查看全校课表</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">毕业设计 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'graduationManagement:student_choose_project' %}">题目浏览</a></li>
            <li><a href="{% url 'graduationManagement:student_submit_project' %}">题目提交</a></li>
            <li><a href="{% url 'graduationManagement:student_view_score' %}">查看成绩</a></li>
        </ul>
    </li>

    <li><a href="{% url 'scoreManagement:assess_teacher' %}">教学评价</a></li>
{% endblock %}


{% block left_side_block %}
    <!-- 不同用户自定义的左侧的侧边栏 -->


    <li class="treeview">
        <a href="{% url 'courseSelection:select_course' %}" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-folder"></i> <span>管理员功能</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span></a>
        <ul class="treeview-menu">
            <li><a href="{% url 'courseSelection:adm_selection_manage' %}">主页</a></li>

            <li><a href="{% url 'courseSelection:adm_school' %}">查询全校选课情况</a></li>
            <li><a href="{% url 'courseSelection:adm_class' %}">查询课程信息</a></li>
        </ul>

    </li>



{% endblock %}
{% block content %}
    <section class="content-header">
        <h1>系统管理员
        </h1>
    </section>
    <form method="post" action="{% url 'courseSelection:class_query' %}">
        {% csrf_token %}
        <section class="content">
            <section class="content">

                <p>时间</p>
                <select name="time">
                    <option value="2018-2019">2018-2019</option>
                    <option value="2017-2018">2017-2018</option>
                    <option value="2016-2017">2016-2017</option>
                </select>
                <p>授课年级</p>
                <select name="grade">
                    <option value="大四">大四</option>
                    <option value="大三">大三</option>
                    <option value="大二">大二</option>
                    <option value="大一">大一</option>
                </select>
                <p>学院</p>
                <select name="college">
                    <option>材料学院</option>
                    <option>信息学院</option>
                    <option>文法学院</option>
                    <option>化工学院</option>
                    <option>材料学院</option>
                    <option>马克思主义学院</option>
                    <option>能源学院</option>

                </select>
                <p>科目</p>
                <select name="subject">
                    <option value="软件工程 ">软件工程</option>

                </select>
                <button id='add' class="btn btn-primary" type="submit" onclick="f()">
                    <span class="glyphicon glyphicon-plus"></span>搜索
                </button>

                <style>
                    .boss {
                        width: 902px;
                        margin: 50px;
                        border: solid 1px red;
                    }

                    .boss div {
                        width: 198px;
                        border: solid 1px gray;
                        float: left;
                    }

                    .boss div img {
                        display: block;
                        width: 100%;
                    }
                </style>

            </section>
        </section>
    </form>
<script>
function f() {
    document.getElementById('box').style.display="block"

}
</script>
{% endblock %}

templates/courseSelection/adm_school.html
{% extends "base.html" %}
{% block title %}欢迎登录教务管理系统{% endblock %}
{% load static %}

{% block custom_nav %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">信息查询 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'backstage:my_personal_details' %}">查看个人信息</a></li>
            <li><a href="#">查看个人课表</a></li>
            <li><a href="#">查看全校课表</a></li>
            <li><a href="#">查询空闲教室</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'scoreManagement:std_view_major_plan' %}">查看专业培养计划</a></li>
            <li><a href="{% url 'scoreManagement:std_view_major_course' %}">查看专业课程计划</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'scoreManagement:student_score' %}">查看考试成绩</a></li>
            <li><a href="{% url 'scoreManagement:student_own_study' %}">查看个人学业情况</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a href="{% url 'courseSelection:select_course' %}" class="dropdown-toggle" data-toggle="dropdown">选课 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'courseSelection:stu_tongshi' %}">通识课</a></li>
            <li><a href="{% url 'courseSelection:stu_major' %}">专业选修</a></li>
            <li><a href="{% url 'courseSelection:adm_selection_manage' %}">管理员界面</a></li>

            <li><a href="#">查看全校课表</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">毕业设计 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'graduationManagement:student_choose_project' %}">题目浏览</a></li>
            <li><a href="{% url 'graduationManagement:student_submit_project' %}">题目提交</a></li>
            <li><a href="{% url 'graduationManagement:student_view_score' %}">查看成绩</a></li>
        </ul>
    </li>

    <li><a href="{% url 'scoreManagement:assess_teacher' %}">教学评价</a></li>
{% endblock %}



{% block left_side_block %}
    <!-- 不同用户自定义的左侧的侧边栏 -->


    <li class="treeview">
        <a href="{% url 'courseSelection:select_course' %}" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-folder"></i> <span>管理员功能</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span></a>
        <ul class="treeview-menu">
            <li><a href="{% url 'courseSelection:adm_selection_manage' %}">主页</a></li>
            <li><a href="{% url 'courseSelection:adm_school' %}">查询全校选课情况</a></li>
            <li><a href="{% url 'courseSelection:adm_class' %}">查询课程信息</a></li>
        </ul>

    </li>



{% endblock %}

{% block content %}
    <section class="content-header">
        <h1>系统管理员
        </h1>
    </section>
    <form method="post" action="{% url 'courseSelection:school_query' %}">
        {% csrf_token %}
        <section class="content">
            <section class="content">
                <p>时间</p>
                <select name="time">
                    <option value="2018-2019">2018-2019</option>
                    <option value="2017-2018">2017-2018</option>
                    <option value="2016-2017">2016-2017</option>
                </select>
                <p>授课年级</p>
                <select name="grade">
                    <option value="大四">大四</option>
                    <option value="大三">大三</option>
                    <option value="大二">大二</option>
                    <option value="大一">大一</option>
                </select>
                <p>学院</p>
                <select name="college">
                    <option value="材料学院">材料学院</option>
                    <option value="信息学院">信息学院</option>
                    <option value="文法学院">文法学院</option>
                    <option value="化工学院">化工学院</option>
                    <option value="材料学院">材料学院</option>
                    <option value="马克思主义学院">马克思主义学院</option>
                    <option value="能源学院">能源学院</option>

                </select>
                <p>科目</p>
                <select name="subject">
                    <option value="软件工程">软件工程</option>

                </select>
                <button type="submit" class="btn btn-primary " onclick="show_img()">搜索</button>
            </section>
        </section>
    </form>

{% endblock %}

templates/courseSelection/adm_selection_manage.html
{% extends "base.html" %}
{% block title %}欢迎登录教务管理系统{% endblock %}

{% block custom_nav %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">信息查询 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'backstage:my_personal_details' %}">查看个人信息</a></li>
            <li><a href="#">查看个人课表</a></li>
            <li><a href="#">查看全校课表</a></li>
            <li><a href="#">查询空闲教室</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'scoreManagement:std_view_major_plan' %}">查看专业培养计划</a></li>
            <li><a href="{% url 'scoreManagement:std_view_major_course' %}">查看专业课程计划</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'scoreManagement:student_score' %}">查看考试成绩</a></li>
            <li><a href="{% url 'scoreManagement:student_own_study' %}">查看个人学业情况</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a href="{% url 'courseSelection:select_course' %}" class="dropdown-toggle" data-toggle="dropdown">选课 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'courseSelection:stu_tongshi' %}">通识课</a></li>
            <li><a href="{% url 'courseSelection:stu_major' %}">专业选修</a></li>
            <li><a href="{% url 'courseSelection:adm_selection_manage' %}">管理员界面</a></li>

            <li><a href="#">查看全校课表</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">毕业设计 <span
                class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'graduationManagement:student_choose_project' %}">题目浏览</a></li>
            <li><a href="{% url 'graduationManagement:student_submit_project' %}">题目提交</a></li>
            <li><a href="{% url 'graduationManagement:student_view_score' %}">查看成绩</a></li>
        </ul>
    </li>

    <li><a href="{% url 'scoreManagement:assess_teacher' %}">教学评价</a></li>
{% endblock %}


{% block left_side_block %}
    <!-- 不同用户自定义的左侧的侧边栏 -->


    <li class="treeview">
        <a href="{% url 'courseSelection:select_course' %}" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-folder"></i> <span>管理员功能</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span></a>
        <ul class="treeview-menu">
            <li><a href="{% url 'courseSelection:adm_selection_manage' %}">主页</a></li>
            <li><a href="{% url 'courseSelection:text' %}">测试</a></li>

            <li><a href="{% url 'courseSelection:adm_school' %}">查询全校选课情况</a></li>
            <li><a href="{% url 'courseSelection:adm_class' %}">查询课程信息</a></li>
        </ul>

    </li>



{% endblock %}
{% block content %}
    <body>

        <form method="post" action="{% url 'courseSelection:time_set' %}">
            {% csrf_token %}
            <h1>设置选课时间</h1>
            <p1>开始时间</p1>
            <input type="datetime-local" value="" name="begin_time"/>
            <p1>结束时间</p1>
            <input type="datetime-local" value=" " name="end_time"/>
            <button type="submit" class="btn btn-primary " onclick="return confirm('Yes/No')">设置</button>
        </form>




    </body>
{% endblock %}
{% block script %}

    <script>

        function Time_set(obj){
            {#alert(obj);#}
                {#alert(obj.name);#}
                $.ajax({
                    url: '/courseSelection/time_set',
                    type: 'POST',

                });
        }

    </script>
{% endblock %}

templates/courseSelection/student_selection_manage.html
{% extends 'student_base.html' %}

templates/courseSelection/teacher_selection_manage.html
{% extends 'teacher_base.html' %}

templates/courseSelection/welcome.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% block title %}选课子系统{% endblock %}